export const translations = {
  en: {
    // App / Loader
    welcome: "Welcome 🙏",
    loading: "Please wait...",

    // Login
    loginTitle: "Chai Bagan",
    loginSub: "Tea Farm Management",
    emailPlaceholder: "Email address",
    passwordPlaceholder: "Password",
    loginBtn: "Login",
    googleBtn: "Continue with Google",
    noAccount: "Don't have an account?",
    register: "Register",
    haveAccount: "Already have an account?",
    loginLink: "Login",
    nameLabel: "Full Name",
    namePlaceholder: "Your name",
    confirmPassword: "Confirm Password",
    registerBtn: "Create Account",
    selectLang: "Select Language",

    // BottomNav
    dashboard: "Dashboard",
    entry: "Entry",
    records: "Records",
    aiChat: "AI Chat",

    // TopBar
    profile: "Profile",
    admin: "Admin",
    user: "User",
    changePassword: "Change Password",
    updateAdvance: "Update Advance",
    clearData: "Clear All Data",
    logout: "Logout",
    language: "Language",
    save: "Save",
    cancel: "Cancel",
    newPassword: "New Password",
    confirmPwd: "Confirm Password",
    advanceAmount: "Advance Amount (Rs)",
    addAdvance: "Add Advance",
    clearConfirm: "Enter password to confirm data deletion",
    totalAdvance: "Total Advance",

    // Dashboard
    dashTitle: "Dashboard",
    totalEarning: "Total Earning",
    received: "Received",
    balance: "Balance",
    advanceTaken: "Advance Taken",
    advanceLeft: "Advance Left",
    recentEntries: "Recent Entries",
    noEntries: "No entries yet",
    addFirst: "Add your first entry from Entry tab",
    month: "Month",
    allMonths: "All Months",

    // Entry Form
    entryTitle: "🍃 Add New Entry 🍃",
    entrySub: "Add date and weight — edit rate later in Records",
    dateLabel: "📅 Date",
    weightLabel: "⚖️ Weight (kg)",
    weightPlaceholder: "e.g. 50 kg",
    submitBtn: "💾 Save Entry",
    submitting: "⏳ Saving...",
    successMsg: "✅ Entry saved successfully!",
    errorRequired: "Date and weight are required!",
    errorWeight: "Enter a valid weight!",

    // Entry View
    monthLabel: "📅 Month:",
    clearBtn: "Clear",
    entriesTotal: "entries total",
    entriesMonth: "entries this month",
    noData: "No entries found",
    noDataSub: "Add new entry from Entry tab",
    rateWait: "Rate Pending",
    balanceLabel: "Balance",
    editBtn: "✏️ Edit / Details",
    deleteTitle: "Delete Entry?",
    deleteMsg: "This entry will be permanently deleted!",
    cancelBtn: "Cancel",
    deleteBtn: "Yes, Delete",
    editTitle: "✏️ Edit Entry",
    weightField: "Weight (kg)",
    rateField: "Rate (Rs/kg)",
    totalField: "Total Amount",
    advCutField: "Advance Cut (Rs)",
    receivedField: "Amount Received (Rs)",
    balanceField: "Balance Amount",
    notesField: "Notes",
    notesPlaceholder: "Any special note...",
    saveBtn: "✅ Save",
    saving: "⏳ Saving...",

    // AI Chat
    chatWelcomeTitle: "Chai Bagan Assistant",
    chatWelcomeSub: "Ask anything about your entries",
    chatHelpTitle: "📋 What can you ask?",
    chatBack: "← Back",
    chatPlaceholder: "Type your question...",
    chatBtns: ["Last Entry", "Balance", "This Month", "Total Earning", "Advance", "Full Report"],
  },

  hi: {
    welcome: "आपका स्वागत है 🙏",
    loading: "कृपया प्रतीक्षा करें...",
    loginTitle: "चाय बागान",
    loginSub: "चाय बाग प्रबंधन",
    emailPlaceholder: "ईमेल पता",
    passwordPlaceholder: "पासवर्ड",
    loginBtn: "लॉगिन करें",
    googleBtn: "Google से जारी रखें",
    noAccount: "खाता नहीं है?",
    register: "रजिस्टर करें",
    haveAccount: "पहले से खाता है?",
    loginLink: "लॉगिन करें",
    nameLabel: "पूरा नाम",
    namePlaceholder: "आपका नाम",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    registerBtn: "खाता बनाएं",
    selectLang: "भाषा चुनें",
    dashboard: "डैशबोर्ड",
    entry: "प्रविष्टि",
    records: "रिकॉर्ड",
    aiChat: "AI चैट",
    profile: "प्रोफाइल",
    admin: "एडमिन",
    user: "यूजर",
    changePassword: "पासवर्ड बदलें",
    updateAdvance: "अग्रिम अपडेट",
    clearData: "सारा डेटा हटाएं",
    logout: "लॉगआउट",
    language: "भाषा",
    save: "सेव करें",
    cancel: "रद्द करें",
    newPassword: "नया पासवर्ड",
    confirmPwd: "पासवर्ड की पुष्टि",
    advanceAmount: "अग्रिम राशि (Rs)",
    addAdvance: "अग्रिम जोड़ें",
    clearConfirm: "डेटा हटाने के लिए पासवर्ड दर्ज करें",
    totalAdvance: "कुल अग्रिम",
    dashTitle: "डैशबोर्ड",
    totalEarning: "कुल कमाई",
    received: "मिली राशि",
    balance: "बाकी राशि",
    advanceTaken: "लिया अग्रिम",
    advanceLeft: "बचा अग्रिम",
    recentEntries: "हाल की प्रविष्टियां",
    noEntries: "अभी कोई प्रविष्टि नहीं",
    addFirst: "प्रविष्टि टैब से पहली प्रविष्टि जोड़ें",
    month: "महीना",
    allMonths: "सभी महीने",
    entryTitle: "🍃 नई प्रविष्टि जोड़ें 🍃",
    entrySub: "तारीख और वजन डालें — हाॅर बाद में रिकॉर्ड में एडिट करें",
    dateLabel: "📅 तारीख",
    weightLabel: "⚖️ वजन (कि.ग्रा.)",
    weightPlaceholder: "जैसे: 50 कि.ग्रा.",
    submitBtn: "💾 प्रविष्टि सेव करें",
    submitting: "⏳ सेव हो रहा है...",
    successMsg: "✅ प्रविष्टि सफलतापूर्वक सेव हुई!",
    errorRequired: "तारीख और वजन जरूरी है!",
    errorWeight: "सही वजन डालें!",
    monthLabel: "📅 महीना:",
    clearBtn: "हटाएं",
    entriesTotal: "कुल प्रविष्टियां",
    entriesMonth: "इस महीने",
    noData: "कोई प्रविष्टि नहीं मिली",
    noDataSub: "प्रविष्टि टैब से नई प्रविष्टि जोड़ें",
    rateWait: "हाॅर बाकी",
    balanceLabel: "बाकी",
    editBtn: "✏️ एडिट / विवरण",
    deleteTitle: "प्रविष्टि हटाएं?",
    deleteMsg: "यह प्रविष्टि हमेशा के लिए हट जाएगी!",
    cancelBtn: "रद्द करें",
    deleteBtn: "हां, हटाएं",
    editTitle: "✏️ प्रविष्टि एडिट करें",
    weightField: "वजन (कि.ग्रा.)",
    rateField: "हाॅर (Rs/कि.ग्रा.)",
    totalField: "कुल राशि",
    advCutField: "अग्रिम कटा (Rs)",
    receivedField: "मिली राशि (Rs)",
    balanceField: "बाकी राशि",
    notesField: "नोट्स",
    notesPlaceholder: "कोई खास बात...",
    saveBtn: "✅ सेव करें",
    saving: "⏳ सेव हो रहा है...",
    chatWelcomeTitle: "चाय बागान सहायक",
    chatWelcomeSub: "अपनी प्रविष्टियों के बारे में कुछ भी पूछें",
    chatHelpTitle: "📋 क्या पूछ सकते हैं?",
    chatBack: "← वापस",
    chatPlaceholder: "प्रश्न लिखें...",
    chatBtns: ["आखिरी प्रविष्टि", "बाकी राशि", "इस महीने", "कुल कमाई", "अग्रिम", "पूरा हिसाब"],
  },

  as: {
    welcome: "আপোনাক স্বাগতম জনালোঁ 🙏",
    loading: "অনুগ্ৰহ কৰি অপেক্ষা কৰক...",
    loginTitle: "চাহ বাগান",
    loginSub: "চাহ বাগান ব্যৱস্থাপনা",
    emailPlaceholder: "ইমেইল ঠিকনা",
    passwordPlaceholder: "পাছৱৰ্ড",
    loginBtn: "লগইন কৰক",
    googleBtn: "Google ৰে অব্যাহত ৰাখক",
    noAccount: "একাউণ্ট নাই?",
    register: "পঞ্জীয়ন কৰক",
    haveAccount: "একাউণ্ট আছে?",
    loginLink: "লগইন কৰক",
    nameLabel: "সম্পূৰ্ণ নাম",
    namePlaceholder: "আপোনাৰ নাম",
    confirmPassword: "পাছৱৰ্ড নিশ্চিত কৰক",
    registerBtn: "একাউণ্ট তৈয়াৰ কৰক",
    selectLang: "ভাষা বাছক",
    dashboard: "ড্যাশব'ৰ্ড",
    entry: "তথ্য",
    records: "ৰেকৰ্ড",
    aiChat: "AI চেট",
    profile: "প্ৰ'ফাইল",
    admin: "এডমিন",
    user: "ব্যৱহাৰকাৰী",
    changePassword: "পাছৱৰ্ড সলনি কৰক",
    updateAdvance: "এডভান্স আপডেট",
    clearData: "সকলো তথ্য মচক",
    logout: "লগআউট",
    language: "ভাষা",
    save: "সংৰক্ষণ কৰক",
    cancel: "বাতিল কৰক",
    newPassword: "নতুন পাছৱৰ্ড",
    confirmPwd: "পাছৱৰ্ড নিশ্চিত কৰক",
    advanceAmount: "এডভান্স পৰিমাণ (Rs)",
    addAdvance: "এডভান্স যোগ কৰক",
    clearConfirm: "তথ্য মচাৰ বাবে পাছৱৰ্ড দিয়ক",
    totalAdvance: "মুঠ এডভান্স",
    dashTitle: "ড্যাশব'ৰ্ড",
    totalEarning: "মুঠ উপাৰ্জন",
    received: "পোৱা পৰিমাণ",
    balance: "বাকী পৰিমাণ",
    advanceTaken: "লোৱা এডভান্স",
    advanceLeft: "বাকী এডভান্স",
    recentEntries: "শেহতীয়া তথ্য",
    noEntries: "কোনো তথ্য নাই",
    addFirst: "তথ্য টেবৰ পৰা প্ৰথম তথ্য যোগ কৰক",
    month: "মাহ",
    allMonths: "সকলো মাহ",
    entryTitle: "🍃 নতুন তথ্য অন্তৰ্ভুক্ত কৰক 🍃",
    entrySub: "তাৰিখ আৰু ওজন দিয়ক — হাৰ পিছত ৰেকৰ্ডত সম্পাদনা কৰক",
    dateLabel: "📅 তাৰিখ",
    weightLabel: "⚖️ ওজন (কি:গ্ৰা:)",
    weightPlaceholder: "যেনে: ৫০ কি:গ্ৰা:",
    submitBtn: "💾 তথ্য অন্তৰ্ভুক্ত কৰক",
    submitting: "⏳ অন্তৰ্ভুক্ত হৈ আছে...",
    successMsg: "✅ তথ্য সফলভাৱে অন্তৰ্ভুক্ত কৰা হ'ল!",
    errorRequired: "তাৰিখ আৰু ওজন বাধ্যতামূলক!",
    errorWeight: "সঠিক ওজন লিখক!",
    monthLabel: "📅 মাহ:",
    clearBtn: "বাতিল",
    entriesTotal: "টা তথ্য মুঠ",
    entriesMonth: "টা তথ্য এই মাহত",
    noData: "কোনো তথ্য পোৱা নগ'ল",
    noDataSub: "তথ্য টেবৰ পৰা নতুন তথ্য যোগ কৰক",
    rateWait: "হিচাব কৰা হোৱা নাই",
    balanceLabel: "বাকী",
    editBtn: "✏️ সম্পাদনা / বিৱৰণ",
    deleteTitle: "তথ্য মচি পেলাব নে?",
    deleteMsg: "এই তথ্য মচি দিয়াৰ পাছত ঘূৰাই নাপাব!",
    cancelBtn: "বাতিল কৰক",
    deleteBtn: "হয়, মচক",
    editTitle: "✏️ তথ্য সম্পাদনা কৰক",
    weightField: "ওজন (কি:গ্ৰা:)",
    rateField: "হাৰ (টকা/কি:গ্ৰা:)",
    totalField: "মুঠ পৰিমাণ",
    advCutField: "এডভান্স কটা (টকা)",
    receivedField: "পোৱা পৰিমাণ (টকা)",
    balanceField: "বাকী পৰিমাণ",
    notesField: "টোকা",
    notesPlaceholder: "কোনো বিশেষ কথা...",
    saveBtn: "✅ সংৰক্ষণ কৰক",
    saving: "⏳ সংৰক্ষণ হৈ আছে...",
    chatWelcomeTitle: "চাহ বাগান সহায়ক",
    chatWelcomeSub: "আপোনাৰ তথ্যৰ বিষয়ে যিকোনো কথা সুধিব পাৰে",
    chatHelpTitle: "📋 কি কি সুধিব পাৰে?",
    chatBack: "← ঘূৰি যাওক",
    chatPlaceholder: "যিকোনো প্ৰশ্ন লিখক...",
    chatBtns: ["শেষ তথ্য", "বাকী পৰিমাণ", "এই মাহ", "মুঠ উপাৰ্জন", "এডভান্স", "সম্পূৰ্ণ হিচাব"],
  },
};

export const langNames = {
  en: "English",
  hi: "हिंदी",
  as: "অসমীয়া",
};
